### PR TITLE
Fix typo in two files

### PR DESCRIPTION
**Pull request by still-flow**
There should be a "-" instead of a "+", I believe.

### CODE REVIEW

**Comment by wspr** [comment]
This looks odd to me, for two reasons. agm.m is pretty fundamental to the rest of the code, so if there are errors here I expect they would have propagated elsewhere. Also, isn't the `A` variable the one with the `+`?

**Comment by rpljwi** [comment]
Sorry, should've mentioned that I was talking about comments, not the actual code.

**Comment by rpljwi** [comment]
Actually... The function defined in agm.m doesn't appear to be called anywhere, funnily enough. elliptic12.m, for example, just uses the same code. Bug?

**Comment by moiseevigor** [comment]
@rpljwi Don't remember exactly, but it was done in this way for optimization purpose.

**Comment by rpljwi** [comment]
Makes sense. One last question (a bit off topic, sorry): there is a inv_agm.m file which contains the same code as agm.m. What's its purpose?

**Pull request merged**
